### PR TITLE
Brandon develop

### LINKED ISSUE #3: Network code refactor
Description: Separate game logic from network code to enable work
to be divided up more easily, allow network code to be
updated/changed, and increase stabilization

Deliverable: Refactored classes divided by network logic and game
logic, with appropriate hooks/sync points.

### LINKED ISSUE #4: Network Error Handling
Description: Currently, the code assumes wifi will never be
lost/interrupted, and no player will ever quit the game. These are
extremely unrealistic expectations. During previous showcases, the
game crashed often, and I constantly had to restart it.

Deliverable: Make the game crash “gracefully,” informing the
facilitator when the game needs to be restarted as well as making
the process of resetting the game as easy and quick as possible.

### PR DESCRIPTION
**Pull request by BrandonSweatman**
Reworked Game, and Network Code.

### CODE REVIEW

**Comment by AvinZarlez** [comment]
I see a lot of code added, but not removed/deprecated. This PR should either remove code that is no longer used, or at the very least mark the files/classes as deprecated / mark for future removal.

**Comment by BrandonSweatman** [comment]
Removed all unused files.

**Comment by AvinZarlez** [comment]
- [ ] Make Controllers Singletons
- [ ] Send player group data not just assign song ID
- [ ] Rename AssignPairs to AssignGroup
- [ ] At end of game return player group (UI can just grab first player from that group!)
- [ ] Can vote during the game
- [ ] Network Error checking code when players drop and rejoin.-

**Comment by BrandonSweatman** [comment]
> * [ ]  Make Controllers Singletons
> * [ ]  Send player group data not just assign song ID
> * [ ]  Rename AssignPairs to AssignGroup
> * [ ]  At end of game return player group (UI can just grab first player from that group!)
> * [ ]  Can vote during the game
> * [ ]  Network Error checking code when players drop and rejoin.-

- Major controllers have been converted to singletons. did my best to debug issues caused by the conversion. GameController remains a reference, as converting a NetworkBehaviour into a singleton casue "Show Stopper" bugs that occurred only in builds.
- Created A method to return a List of players assigned to a a specific songID. this songID effectively acts as a group Id Number.
- AssignPairs renamed to AssignPlayerGroups. Felt a more explicit name was called for.
- end game scenario now grabs the group of players that are not the local player, and displays the first player in the group.
- Network error code now displays a popup for better user experience.
- Added in additional messaging for networking AutoConnect Feature for better user experience.

TODO
- add in ability to vote during game play.

The conversion to singletons added a great deal more errors and bugs that I had not anticipated. mostly race conditions. a good deal of time was spent tracking them all down and finding an appropriate fix. now that the app seems to be in a solid state once more, I can add in the remaining functionality.

**Comment by AvinZarlez** [comment]
For remaining functionality, remember to just focus on the network system and error checking/handling, etc.

Is there any more that needs to be implemented? Any other outstanding bugs to investigate?

**Comment by AvinZarlez** [comment]
Just asking for FYI. I won't have the time to test this for a few days. Long story short, I'm having a particularly bad week.

**Comment by BrandonSweatman** [comment]
I just have to implement the vote during gameplay feature. 
Right now I have seemingly fixed any of the bugs that I have witnessed.

No rush, sorry to hear about your week. May it improve!

**Comment by BrandonSweatman** [comment]
Added in a very simple player select in the active game player select. if a player is selected, a box will appear around the button for said player, and will turn green if selection is correct, or red if the selection is incorrect.

end game view, and post game view will show the first player selected for now.

further work will need to be done to visually handle group selection, but support is there in the code base.

**Comment by AvinZarlez** [comment]
I'm so sorry I still haven't gotten a chance to play around with this. It's been an extremely hectic time in general for me.

I will soon. Just wanted to say I hadn't forgotten, but also haven't been able to dive in.

Do you want to schedule another call to talk over things?

**Comment by BrandonSweatman** [comment]
I fully understand. Yeah we should schedule another meeting. There is a
lots I can still show you.

**Pull request merged**
